version: '3'

services:
  go_library_db:
    container_name: go_library_db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go_db_network
  go_library_app:
    container_name: go_library_app
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - go_library_db
      - migrations
    networks:
      - go_db_network
  migrations:
    container_name: migrations
    image: ghcr.io/kukymbr/goose-docker:3.15.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=go_library_db port=5432 user=admin password=admin123 dbname=postgres
    volumes:
      - ./repository/migrations:/migrations
    restart: always
    depends_on:
      - go_library_db
    networks:
      - go_db_network
volumes:  
  pgdata: {}

networks:
  go_db_network:
    driver: bridge