CREATE TABLE books (
  id  SERIAL PRIMARY KEY,
  name text NOT NULL,
  author text NOT NULL
);


CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(20) NOT NULL
);

CREATE TABLE user_books (
id SERIAL PRIMARY KEY,
user_id INT NOT NULL,
book_id INT NOT NULL,
date DATE NOT NULL,
status VARCHAR(100) NOT NULL
);